import { JobList } from '@/components/job-list';
import { JobPost, MyCollections } from '@/types';
import { Box, Heading, Input, Stack } from '@chakra-ui/react';
import { Directus } from '@directus/sdk';
import Head from 'next/head';

export default function Home({ jobs }: { jobs: JobPost[] }) {
  return (
    <>
      <Head>
        <title>Job board</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box p={{ base: '12', lg: '24' }}>
        <Stack mb='8' maxW='sm'>
          <Heading>Find Your Dream Job</Heading>
          <Input placeholder='Search for a job' />
        </Stack>
        <JobList data={jobs} />
      </Box>
    </>
  );
}

export const getStaticProps = async () => {
  const directus = new Directus<MyCollections>(
    'https://esther-dev.directus.app/'
  );

  // await directus.auth.static('<api-token>');

  const jobs = await directus.items('jobs').readByQuery({
    limit: -1,
    fields: ['*'],
  });

  // format the image field to have the full url
  jobs.data?.forEach((job) => {
    job.logo = `https://esther-dev.directus.app/assets/${job.logo}`;
  });

  return {
    props: {
      jobs: jobs.data,
    },
  };
};
